import path from 'node:path';
import {configGet} from './steps/config-get.js';
import {resetActions} from './steps/reset-actions.js';
import {searchActionNames} from './steps/search-action-names.js';
import {extractFunctionParts} from './steps/extract-function-parts.js';
import {publishAction} from './steps/publish-action.js';
import {publishActionsIndex} from './steps/publish-actions-index.js';
import {publishTypes} from './steps/publish-types.js';

const notice = `
/**
 * !! DO NOT EDIT THIS FILE MANUALLY !!
 * This file is generated by action-api-cli.
 * If you want to change the contents, please edit the source code and run the codegen command again.
 */
`.trimStart();

/**
 * @param {object} event
 * @param {string} event.cwd
 * @param {string[]} event.options
 * @returns {Promise<void>}
 */
export async function codegen(event) {
	const {cwd, options} = event;
	const {source, output} = await configGet({cwd, options});
	await resetActions(output);
	const actionNames = await searchActionNames(source);
	await Promise.all(actionNames.map(async actionName => {
		const sourcePath = path.join(source, actionName, 'index.js');
		const outPath = path.join(output, actionName, 'index.js');
		const {docComment, inputName} = await extractFunctionParts(sourcePath);
		await publishAction({
			outPath,
			actionName,
			docComment,
			inputName,
			notice,
		});
	}));
	await publishActionsIndex({
		outPath: path.join(output, 'index.js'),
		actionNames,
		notice,
	});
	await publishTypes({
		sourcePath: source,
		outPath: output,
	});
}
